apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: user-service-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
  - name: user-service.rules
    rules:
    - alert: HighCPUUsage
      expr: sum(rate(container_cpu_usage_seconds_total{namespace="default", pod=~"user-service.*"}[2m])) > 0.2
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage detected for user-service"
        description: "Pod in user-service namespace using high CPU for more than 1 minute."
    - alert: PodRestartingFrequently
      expr: increase(kube_pod_container_status_restarts_total{namespace="default", pod=~"user-service.*"}[5m]) > 3
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Pod restarting frequently"
        description: "Pod in user-service restarted more than 3 times in the last 5 minutes."
